### ISSUE TITLE
Search Type multipleselect for Many-to-Many relationship

### ISSUE THREAD

**Issue by jworley** [scherersoftware/cake-list-filter#2]
Is there a way to use the multipleselect search type for Many-to-Many relationships, for example to filter on Tags.

**Comment by cleptric** [comment]
@jworley For now, the only possibility is to pass a custom matching query to the paginator in the controller.

**Comment by cleptric** [comment]
@jworley For now you have to use a custom matching query in the controller to accomplish many to many filtering. We doesn't provide a multi select filter input because of this.
