### ISSUE TITLE
resetButton deletes given params

### ISSUE THREAD

**Issue by manuelmiksche** [scherersoftware/cake-list-filter#3]
A click on the listFilter resetButton deletes the passed params e.g. "/action/36a3a3f1-0dbe-4992-af6f-26bdcd68ea1c" results in "/action/?passed=36a3a3f1-0dbe-4992-af6f-26bdcd68ea1c" and throws an error if the passed parameter is required by the action to work properly.

**Comment by cleptric** [comment]
Fixed in v1.3.0
